### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by I3alaa** [Puyodead1/EnchantCrystals#5]
While I was testing the plugin it appears if an enchantment crystal has multiple enchants and I would like to add it to a tool that already has higher enchantments it will be duplicated, it won't work with enchantment crystals that has only one enchantment.

**Comment by Puyodead1** [comment]
Thank you for the report, I will look into this today.

**Comment by Puyodead1** [comment]
> 
> 
> While I was testing the plugin it appears if an enchantment crystal has multiple enchants and I would like to add it to a tool that already has higher enchantments it will be duplicated, it won't work with enchantment crystals that has only one enchantment.

Can you possibly write out the steps to reproduce this? I tried with a crystal that had Sharpness 2 and looting 3 and applied it to a sword with sharpness 3 and it correctly bumped sharpness from 3 to 5. 

I also tried with sharpness 5 and looting 3 and applied it to a sword with sharpness 5 and it also correctly applies the looting only and left the crystal with sharpness 5

**Comment by I3alaa** [comment]
I've made a quick vid about it so it might be easier to understand.

https://www.youtube.com/watch?v=S66q16CYtQc

**Comment by Puyodead1** [comment]
> 
> 
> I've made a quick vid about it so it might be easier to understand.
> 
> https://www.youtube.com/watch?v=S66q16CYtQc

yikes, alright. Thank you for making the video.

**Comment by I3alaa** [comment]
No worries, happy to help :D
